### ISSUE TITLE
checkTargetingRadius

### ISSUE THREAD

**Issue by Krabbcakes** [Krabbcakes/OA#4]
checkTargetingRadius function inside PlayerOA file doesn't work.  Trying to get turrets to check for enemies within the targetingRadius using a distance formula.  

currently getting this error:

PlayerOA.js:30 Uncaught ReferenceError: checkTargetingRadius is not defined
    at Turret.update (PlayerOA.js:30)

    at turretUpdate (GameBoardOA.js:42)
    at updateAll (MainOA.js:30)

**Comment by sjdodge123** [comment]
The error is telling you that the call in the turretUpdate calling checkTargetingRadius is invalid

looks like you've defined checkTargetingRadius as a function of the class Turrent, which is fine, but when you call that function you need to reference the turret. If calling from itself, you need this.checkTargetingRadius, if external, turret.checkTargeting Radius

**Comment by Krabbcakes** [comment]
doh, thanks
